### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [SafeInsure/sins-coin#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

**Comment by SafeInsure** [comment]
Please specify the files from which PIVX developers were excluded.

**Comment by Iconoclasta** [comment]
Please include the `PIVX` name.

**Comment by qyno** [comment]
"The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights."

Show me a file where PivX developers were excluded from copyright headers in source files!

**Comment by qyno** [comment]
Please check and then make accusations

**Comment by Iconoclasta** [comment]
How about you start with the general license itself and work up from there?


      sins-coin/COPYING

**Comment by SafeInsure** [comment]
There you are right, I corrected. Something else?

**Comment by Iconoclasta** [comment]
I have reviewed your codebase and indeed everything seems in order now. Thank you for your collaboration.
