### ISSUE TITLE
Masternode installation

### ISSUE THREAD

**Issue by 123pda** [SafeInsure/sins-coin#6]
Hey guys, the manual for setting up a Masternode at Ubuntu is not correct. Trying it on various machines, it did not work out. Something is definitely missing there, and I have no clue what it is...
After all, I get a "timeout" as a reason for the daemon not to start up (see also attachment).
![unbenannt](https://user-images.githubusercontent.com/47091497/51807976-58b1d900-2296-11e9-9e06-1f635f5bfe6e.PNG)

**Comment by pwte** [comment]
**The installation script only works for root!!**
